-- Insert comprehensive JEE chapters data for Physics, Chemistry, and Mathematics

-- Physics Chapters (29 chapters)
INSERT INTO chapters (subject, chapter_name, chapter_number, description, difficulty_level, estimated_time, is_free, is_premium) VALUES
('Physics', 'Units and Measurements', 1, 'Fundamental units, dimensional analysis, significant figures', 'easy', 4, true, false),
('Physics', 'Motion in a Straight Line', 2, 'Kinematics, velocity, acceleration, equations of motion', 'easy', 5, true, false),
('Physics', 'Motion in a Plane', 3, 'Projectile motion, circular motion, relative velocity', 'medium', 6, true, false),
('Physics', 'Laws of Motion', 4, 'Newton''s laws, friction, circular motion dynamics', 'medium', 8, false, true),
('Physics', 'Work, Energy and Power', 5, 'Work-energy theorem, conservation of energy, power', 'medium', 7, false, true),
('Physics', 'System of Particles and Rotational Motion', 6, 'Center of mass, angular momentum, moment of inertia', 'hard', 10, false, true),
('Physics', 'Gravitation', 7, 'Universal gravitation, Kepler''s laws, satellites', 'medium', 6, false, true),
('Physics', 'Mechanical Properties of Solids', 8, 'Stress, strain, elastic modulus, Hooke''s law', 'medium', 5, false, true),
('Physics', 'Mechanical Properties of Fluids', 9, 'Pressure, buoyancy, Bernoulli''s theorem, viscosity', 'medium', 6, false, true),
('Physics', 'Thermal Properties of Matter', 10, 'Heat transfer, thermal expansion, calorimetry', 'easy', 5, false, true),
('Physics', 'Thermodynamics', 11, 'Laws of thermodynamics, heat engines, entropy', 'hard', 8, false, true),
('Physics', 'Kinetic Theory', 12, 'Ideal gas equation, kinetic energy, mean free path', 'medium', 5, false, true),
('Physics', 'Oscillations', 13, 'Simple harmonic motion, pendulum, springs', 'medium', 7, false, true),
('Physics', 'Waves', 14, 'Wave motion, interference, beats, Doppler effect', 'hard', 8, false, true),
('Physics', 'Electric Charges and Fields', 15, 'Coulomb''s law, electric field, Gauss''s law', 'medium', 7, false, true),
('Physics', 'Electrostatic Potential and Capacitance', 16, 'Potential energy, capacitors, dielectrics', 'hard', 8, false, true),
('Physics', 'Current Electricity', 17, 'Ohm''s law, Kirchhoff''s laws, Wheatstone bridge', 'medium', 7, false, true),
('Physics', 'Moving Charges and Magnetism', 18, 'Magnetic force, Biot-Savart law, Ampere''s law', 'hard', 9, false, true),
('Physics', 'Magnetism and Matter', 19, 'Bar magnets, magnetic properties, hysteresis', 'medium', 5, false, true),
('Physics', 'Electromagnetic Induction', 20, 'Faraday''s law, Lenz''s law, eddy currents', 'hard', 8, false, true),
('Physics', 'Alternating Current', 21, 'AC circuits, impedance, resonance, transformers', 'hard', 9, false, true),
('Physics', 'Electromagnetic Waves', 22, 'Maxwell''s equations, EM spectrum, wave propagation', 'medium', 5, false, true),
('Physics', 'Ray Optics and Optical Instruments', 23, 'Reflection, refraction, lenses, microscopes', 'medium', 7, false, true),
('Physics', 'Wave Optics', 24, 'Interference, diffraction, polarization', 'hard', 7, false, true),
('Physics', 'Dual Nature of Radiation and Matter', 25, 'Photoelectric effect, de Broglie wavelength', 'medium', 6, false, true),
('Physics', 'Atoms', 26, 'Bohr model, hydrogen spectrum, X-rays', 'medium', 6, false, true),
('Physics', 'Nuclei', 27, 'Radioactivity, nuclear reactions, binding energy', 'hard', 7, false, true),
('Physics', 'Semiconductor Electronics', 28, 'Diodes, transistors, logic gates', 'medium', 8, false, true),
('Physics', 'Communication Systems', 29, 'Modulation, transmission, bandwidth', 'easy', 4, false, true),

-- Chemistry Chapters (29 chapters)
('Chemistry', 'Some Basic Concepts of Chemistry', 1, 'Atomic mass, mole concept, stoichiometry', 'easy', 5, true, false),
('Chemistry', 'Structure of Atom', 2, 'Quantum numbers, orbitals, electronic configuration', 'medium', 6, true, false),
('Chemistry', 'Classification of Elements and Periodicity', 3, 'Periodic table, trends, properties', 'easy', 5, true, false),
('Chemistry', 'Chemical Bonding and Molecular Structure', 4, 'Ionic, covalent bonds, VSEPR, hybridization', 'hard', 8, false, true),
('Chemistry', 'States of Matter', 5, 'Gas laws, liquid state, solid state', 'medium', 6, false, true),
('Chemistry', 'Thermodynamics', 6, 'Enthalpy, entropy, Gibbs energy', 'hard', 8, false, true),
('Chemistry', 'Equilibrium', 7, 'Chemical equilibrium, Le Chatelier''s principle', 'medium', 7, false, true),
('Chemistry', 'Redox Reactions', 8, 'Oxidation states, balancing equations, electrochemistry', 'medium', 6, false, true),
('Chemistry', 'Hydrogen', 9, 'Properties, isotopes, hydrides', 'easy', 4, false, true),
('Chemistry', 'The s-Block Elements', 10, 'Alkali and alkaline earth metals', 'medium', 5, false, true),
('Chemistry', 'The p-Block Elements', 11, 'Group 13-18 elements, properties', 'hard', 9, false, true),
('Chemistry', 'Organic Chemistry - Basic Principles', 12, 'IUPAC nomenclature, isomerism, GOC', 'hard', 10, false, true),
('Chemistry', 'Hydrocarbons', 13, 'Alkanes, alkenes, alkynes, aromatic compounds', 'hard', 9, false, true),
('Chemistry', 'Environmental Chemistry', 14, 'Pollution, ozone layer, greenhouse effect', 'easy', 4, false, true),
('Chemistry', 'Solid State', 15, 'Crystal lattices, unit cells, defects', 'medium', 6, false, true),
('Chemistry', 'Solutions', 16, 'Molarity, colligative properties, Raoult''s law', 'medium', 7, false, true),
('Chemistry', 'Electrochemistry', 17, 'Galvanic cells, Nernst equation, electrolysis', 'hard', 8, false, true),
('Chemistry', 'Chemical Kinetics', 18, 'Rate laws, order, Arrhenius equation', 'hard', 7, false, true),
('Chemistry', 'Surface Chemistry', 19, 'Adsorption, catalysis, colloids', 'medium', 5, false, true),
('Chemistry', 'General Principles of Metallurgy', 20, 'Extraction, refining, thermodynamics', 'medium', 6, false, true),
('Chemistry', 'The d and f Block Elements', 21, 'Transition metals, lanthanides, actinides', 'hard', 8, false, true),
('Chemistry', 'Coordination Compounds', 22, 'Nomenclature, isomerism, bonding theories', 'hard', 7, false, true),
('Chemistry', 'Haloalkanes and Haloarenes', 23, 'Preparation, properties, reactions', 'medium', 6, false, true),
('Chemistry', 'Alcohols, Phenols and Ethers', 24, 'Classification, preparation, reactions', 'medium', 7, false, true),
('Chemistry', 'Aldehydes, Ketones and Carboxylic Acids', 25, 'Preparation, properties, reactions', 'hard', 8, false, true),
('Chemistry', 'Amines', 26, 'Classification, preparation, chemical properties', 'medium', 6, false, true),
('Chemistry', 'Biomolecules', 27, 'Carbohydrates, proteins, nucleic acids', 'medium', 7, false, true),
('Chemistry', 'Polymers', 28, 'Classification, polymerization, properties', 'easy', 5, false, true),
('Chemistry', 'Chemistry in Everyday Life', 29, 'Drugs, detergents, chemicals', 'easy', 4, false, true),

-- Mathematics Chapters (25 chapters)
('Mathematics', 'Sets, Relations and Functions', 1, 'Set theory, relations, types of functions', 'easy', 5, true, false),
('Mathematics', 'Complex Numbers', 2, 'Algebra of complex numbers, Argand plane, De Moivre''s theorem', 'medium', 6, true, false),
('Mathematics', 'Quadratic Equations', 3, 'Roots, discriminant, quadratic inequalities', 'easy', 5, true, false),
('Mathematics', 'Sequences and Series', 4, 'AP, GP, HP, special series', 'medium', 7, false, true),
('Mathematics', 'Permutations and Combinations', 5, 'Fundamental principle, arrangements, selections', 'hard', 8, false, true),
('Mathematics', 'Binomial Theorem', 6, 'Expansion, general term, coefficients', 'medium', 6, false, true),
('Mathematics', 'Matrices and Determinants', 7, 'Matrix operations, determinants, inverse', 'hard', 9, false, true),
('Mathematics', 'Probability', 8, 'Basic probability, conditional probability, Bayes theorem', 'hard', 8, false, true),
('Mathematics', 'Mathematical Induction', 9, 'Principle of induction, applications', 'medium', 5, false, true),
('Mathematics', 'Mathematical Reasoning', 10, 'Statements, logical operations, validity', 'easy', 4, false, true),
('Mathematics', 'Statistics', 11, 'Mean, median, mode, standard deviation', 'easy', 5, false, true),
('Mathematics', 'Trigonometry', 12, 'Ratios, identities, equations, inverse functions', 'medium', 8, false, true),
('Mathematics', 'Limits and Continuity', 13, 'Limits, continuity, differentiability', 'medium', 7, false, true),
('Mathematics', 'Differentiation', 14, 'Derivatives, chain rule, implicit differentiation', 'hard', 8, false, true),
('Mathematics', 'Application of Derivatives', 15, 'Tangents, normals, maxima-minima, rate of change', 'hard', 9, false, true),
('Mathematics', 'Indefinite Integration', 16, 'Integration methods, substitution, partial fractions', 'hard', 9, false, true),
('Mathematics', 'Definite Integration', 17, 'Fundamental theorem, properties, applications', 'hard', 8, false, true),
('Mathematics', 'Area Under Curves', 18, 'Applications of integration', 'medium', 6, false, true),
('Mathematics', 'Differential Equations', 19, 'Formation, solutions, types of DE', 'hard', 8, false, true),
('Mathematics', 'Vectors', 20, 'Vector algebra, scalar and vector products', 'medium', 7, false, true),
('Mathematics', 'Three Dimensional Geometry', 21, 'Direction cosines, lines, planes', 'hard', 8, false, true),
('Mathematics', 'Straight Lines', 22, 'Slope, equations, distance, locus', 'easy', 5, false, true),
('Mathematics', 'Circles', 23, 'Standard equations, tangents, chords', 'medium', 6, false, true),
('Mathematics', 'Conic Sections', 24, 'Parabola, ellipse, hyperbola', 'hard', 9, false, true),
('Mathematics', 'Linear Programming', 25, 'Formulation, graphical method, optimization', 'medium', 6, false, true);
